/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as OrigenRouteImport } from './routes/origen'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminRecipesRouteImport } from './routes/admin/recipes'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminRecipesNewRouteImport } from './routes/admin/recipes.new'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products.new'
import { Route as AdminRecipesIdEditRouteImport } from './routes/admin/recipes.$id.edit'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin/products.$id.edit'

const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const OrigenRoute = OrigenRouteImport.update({
  id: '/origen',
  path: '/origen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesRoute = AdminRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesNewRoute = AdminRecipesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRecipesRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesIdEditRoute = AdminRecipesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminRecipesRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/origen': typeof OrigenRoute
  '/tienda': typeof TiendaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/recipes': typeof AdminRecipesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/recipes/$id/edit': typeof AdminRecipesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/origen': typeof OrigenRoute
  '/tienda': typeof TiendaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/recipes': typeof AdminRecipesRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/recipes/$id/edit': typeof AdminRecipesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/origen': typeof OrigenRoute
  '/tienda': typeof TiendaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/recipes': typeof AdminRecipesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/recipes/new': typeof AdminRecipesNewRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/recipes/$id/edit': typeof AdminRecipesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/origen'
    | '/tienda'
    | '/admin/login'
    | '/admin/recipes'
    | '/admin/'
    | '/admin/products/new'
    | '/admin/recipes/new'
    | '/admin/products/$id/edit'
    | '/admin/recipes/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/origen'
    | '/tienda'
    | '/admin/login'
    | '/admin/recipes'
    | '/admin'
    | '/admin/products/new'
    | '/admin/recipes/new'
    | '/admin/products/$id/edit'
    | '/admin/recipes/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/origen'
    | '/tienda'
    | '/admin/login'
    | '/admin/recipes'
    | '/admin/'
    | '/admin/products/new'
    | '/admin/recipes/new'
    | '/admin/products/$id/edit'
    | '/admin/recipes/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  OrigenRoute: typeof OrigenRoute
  TiendaRoute: typeof TiendaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origen': {
      id: '/origen'
      path: '/origen'
      fullPath: '/origen'
      preLoaderRoute: typeof OrigenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes': {
      id: '/admin/recipes'
      path: '/recipes'
      fullPath: '/admin/recipes'
      preLoaderRoute: typeof AdminRecipesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes/new': {
      id: '/admin/recipes/new'
      path: '/new'
      fullPath: '/admin/recipes/new'
      preLoaderRoute: typeof AdminRecipesNewRouteImport
      parentRoute: typeof AdminRecipesRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes/$id/edit': {
      id: '/admin/recipes/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/recipes/$id/edit'
      preLoaderRoute: typeof AdminRecipesIdEditRouteImport
      parentRoute: typeof AdminRecipesRoute
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRecipesRouteChildren {
  AdminRecipesNewRoute: typeof AdminRecipesNewRoute
  AdminRecipesIdEditRoute: typeof AdminRecipesIdEditRoute
}

const AdminRecipesRouteChildren: AdminRecipesRouteChildren = {
  AdminRecipesNewRoute: AdminRecipesNewRoute,
  AdminRecipesIdEditRoute: AdminRecipesIdEditRoute,
}

const AdminRecipesRouteWithChildren = AdminRecipesRoute._addFileChildren(
  AdminRecipesRouteChildren,
)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRecipesRoute: typeof AdminRecipesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminRecipesRoute: AdminRecipesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  OrigenRoute: OrigenRoute,
  TiendaRoute: TiendaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
